// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlfizuhzrescxnueluii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZml6dWh6cmVzY3hudWVsdWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwODI2MzcsImV4cCI6MjA1NTY1ODYzN30.tf3PhLLnUz7cbh92ds94J1uL9ABhwt_MqsRRHxZKEwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);